### ISSUE TITLE
Defaulting to IRIS page

### ISSUE THREAD

**Issue by tommorgan365** [weslambert/velocistack#14]
Hello,
Putting in  https://IP/velocistack and I get page not found and redirects to Iris.
Message on page is 
SORRY!
The page you’re looking for was not found.
Any suggestions on this one?

**Comment by rjonhaas** [comment]
Running into the same issue. Looks like all of the dockers are up:


[dockerps.txt](https://github.com/weslambert/velocistack/files/11046037/dockerps.txt)

**Comment by weslambert** [comment]
I just tested this recently and don't recall running into this issue, but I'll check again. Thanks!

**Comment by weslambert** [comment]
I tested this not long ago and did not receive the IRIS page, but an error, so I am looking into it.

**Comment by 0ptsec** [comment]
I would imagine this in inline with the IRIS page. If you want me to create an additional issue, I will. Getting an nginx 502 bad gateway error when navigating to IRIS.
IRIS-web logs are below:
db:5432 - accepting connections
Running iriswebapp ...
[2023-04-26 20:24:33 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-04-26 20:24:33 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
[2023-04-26 20:24:33 +0000] [7] [INFO] Using worker: eventlet
[2023-04-26 20:24:33 +0000] [12] [INFO] Booting worker with pid: 12
[2023-04-26 20:24:35 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
    super().init_process()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/iriswebapp/app/__init__.py", line 26, in <module>
    from flask_bcrypt import Bcrypt
  File "/opt/venv/lib/python3.9/site-packages/flask_bcrypt.py", line 21, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/opt/venv/lib/python3.9/site-packages/werkzeug/security.py)
[2023-04-26 20:24:35 +0000] [12] [INFO] Worker exiting (pid: 12)
[2023-04-26 20:24:36 +0000] [7] [INFO] Shutting down: Master
[2023-04-26 20:24:36 +0000] [7] [INFO] Reason: Worker failed to boot.

**Comment by weslambert** [comment]
Thanks! I'll take a look.

**Comment by weslambert** [comment]
This should be fixed. Please re-open this issue if you still have problems.
