### ISSUE TITLE
Iris does not load

### ISSUE THREAD

**Issue by hasamba** [weslambert/velocistack#18]
getting 502 bad gateway, 

iris-web log:
`Running iriswebapp ...
[2023-10-18 09:48:58 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-10-18 09:48:58 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
[2023-10-18 09:48:58 +0000] [8] [INFO] Using worker: eventlet
[2023-10-18 09:48:58 +0000] [10] [INFO] Booting worker with pid: 10
[2023-10-18 09:48:59 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
    super().init_process()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/iriswebapp/app/__init__.py", line 29, in <module>
    from flask_login import LoginManager
  File "/opt/venv/lib/python3.9/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/opt/venv/lib/python3.9/site-packages/flask_login/login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "/opt/venv/lib/python3.9/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/opt/venv/lib/python3.9/site-packages/werkzeug/urls.py)
[2023-10-18 09:48:59 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-10-18 09:48:59 +0000] [8] [INFO] Shutting down: Master
[2023-10-18 09:48:59 +0000] [8] [INFO] Reason: Worker failed to boot.`

iris worker log:
`IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping
IRISwebapp is unavailable - sleeping`

**Comment by weslambert** [comment]
I've updated the stack. Please test again and re-open the issue if it doesn't work for you.
